BEGIN TRANSACTION;
CREATE TABLE tag (id_tag INTEGER PRIMARY KEY AUTOINCREMENT,  value varchar(128) NOT NULL, id_type INTEGER NOT NULL, id_tag_ref INTEGER, FOREIGN KEY(id_type) REFERENCES type(id_type), FOREIGN KEY(id_tag_ref) REFERENCES tag(id_tag));
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (1,'secured',4,NULL);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (2,'validate',4,NULL);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (3,'huntington',1,NULL);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (4,'MR',2,NULL);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (5,'IRM',2,4);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (6,'MRI',2,4);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (7,'US',2,NULL);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (8,'echo',2,7);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (9,'angio',2,NULL);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (10,'leaver',6,'');
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (11,'foie',6,10);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (12,'brain',6,NULL);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (13,'cerveau',6,12);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (14,'skull',6,12);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (15,'crane',6,12);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (16,'heart',6,NULL);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (17,'coeur',6,16);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (18,'2D',9,NULL);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (19,'3D',9,'');
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (20,'2D+t',9,NULL);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (21,'3D+t',9,NULL);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (22,'video',9,NULL);
INSERT INTO `tag` (id_tag,value,id_type,id_tag_ref) VALUES (23,'vidéo',9,22);
COMMIT;
